### ISSUE TITLE
.gitignore 추가하기

### ISSUE THREAD

**Issue by rubycho** [agurimon/JungYoon-World#11]
소스 이외의 불필요한 파일들(pycache, bower의 lib, venv 등...)은 제거하는 게 좋습니다.
라이브러리, 가상 환경은 클론 후 로컬 환경에서 설치할 수 있으니까요.
(bower.json, requirements.txt가 존재하는 이유이기도 합니다)

레포에 적절한 .gitignore 파일을 추가하고 
이미 올린 불필요한 파일들에 대해서는 git rm을 사용하는 건 어떨까요?

**Comment by agurimon** [comment]
와우 이걸 몰라서 맨날 이메일 날라왔어요 ㅠㅠㅠㅠㅠ
Thanks!!!
